version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: mealuser
      POSTGRES_PASSWORD: mealpass
      POSTGRES_DB: mealplanner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: