/* istanbul ignore file -- pure type re-exports, no runtime logic to cover */
// Import protobuf types from generated package
export {
  Ingredient,
  Step,
  Meal,
  ShoppingListItem,
} from '@mealplanner/generated/api_pb';

// Re-export all other types from proto-generated package
export {
  MealPlan,
  MealPlanItem,
  MealPlanEntry,
  MealPlanSummary,
  MealPlanStatus,
  MealSlot,
  WorkflowStatus,
  HealthCheckResponse,
  GetMealPlanResponse,
  GenerateMealPlanResponse,
  FinalizeMealPlanRequest,
  FinalizeMealPlanResponse,
  GetShoppingListRequest,
  GetShoppingListResponse,
  GetAllMealsRequest,
  GetAllMealsResponse,
  CreateMealRequest,
  CreateMealResponse,
  SwapMealRequest,
  SwapMealResponse,
  ReplaceMealRequest,
  ReplaceMealResponse,
  UpdateMealIngredientRequest,
  UpdateMealIngredientResponse,
  DeleteMealIngredientRequest,
  DeleteMealIngredientResponse,
  DeleteMealRequest,
  DeleteMealResponse,
  GetStepsRequest,
  GetStepsResponse,
  AddStepRequest,
  AddStepResponse,
  AddBulkStepsRequest,
  AddBulkStepsResponse,
  UpdateStepRequest,
  UpdateStepResponse,
  DeleteStepRequest,
  DeleteStepResponse,
  ReorderStepsRequest,
  ReorderStepsResponse,
  DeleteAllStepsRequest,
  DeleteAllStepsResponse,
} from '@mealplanner/generated/api_pb';
