/* istanbul ignore file -- pure type re-exports, no runtime logic to cover */
// Import protobuf types from generated package
export type {
  Ingredient,
  Step,
  Meal,
  ShoppingListItem,
} from '@mealplanner/generated';

// Re-export all other types from proto-generated package
export type {
  WeeklyMealPlan,
  AgentStartRequest,
  AgentFeedbackRequest,
  AgentResumeRequest,
  AgentMessageRequest,
  AgentResponse,
  WorkflowStatus,
  HealthCheckResponse,
  GetMealPlanResponse,
  GenerateMealPlanResponse,
  FinalizeMealPlanRequest,
  FinalizeMealPlanResponse,
  GetShoppingListRequest,
  GetShoppingListResponse,
  GetAllMealsRequest,
  GetAllMealsResponse,
  CreateMealRequest,
  CreateMealResponse,
  SwapMealRequest,
  SwapMealResponse,
  ReplaceMealRequest,
  ReplaceMealResponse,
  UpdateMealIngredientRequest,
  UpdateMealIngredientResponse,
  DeleteMealIngredientRequest,
  DeleteMealIngredientResponse,
  DeleteMealRequest,
  DeleteMealResponse,
  GetStepsRequest,
  GetStepsResponse,
  AddStepRequest,
  AddStepResponse,
  AddBulkStepsRequest,
  AddBulkStepsResponse,
  UpdateStepRequest,
  UpdateStepResponse,
  DeleteStepRequest,
  DeleteStepResponse,
  ReorderStepsRequest,
  ReorderStepsResponse,
  DeleteAllStepsRequest,
  DeleteAllStepsResponse,
  StartAgentWorkflowRequest,
  StartAgentWorkflowResponse,
  MessageAgentRequest,
  MessageAgentResponse,
  GetWorkflowStatusRequest,
  GetWorkflowStatusResponse,
  ListWorkflowsResponse,
  CancelWorkflowRequest,
  CancelWorkflowResponse,
  GetWorkflowStateRequest,
  GetWorkflowStateResponse,
  AbandonWorkflowRequest,
  AbandonWorkflowResponse,
  AddMessageRequest,
  AddMessageResponse,
} from '@mealplanner/generated';
