// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agent/message": {
            "post": {
                "description": "Send a message to an existing agent workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Message Agent",
                "parameters": [
                    {
                        "description": "Agent message request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.AgentMessageRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message sent successfully",
                        "schema": {
                            "$ref": "#/definitions/main.AgentMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/agent/start": {
            "post": {
                "description": "Start a new agent workflow for meal planning",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Start Agent Workflow",
                "parameters": [
                    {
                        "description": "Agent start request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.AgentStartRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Agent workflow started successfully",
                        "schema": {
                            "$ref": "#/definitions/main.AgentStartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/agent/status/{threadId}": {
            "get": {
                "description": "Get the status of an agent workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Get Workflow Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "threadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workflow status retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.WorkflowStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/agent/workflows": {
            "get": {
                "description": "List all active workflows",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "List Workflows",
                "responses": {
                    "200": {
                        "description": "Workflows listed successfully",
                        "schema": {
                            "$ref": "#/definitions/main.WorkflowsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/agent/workflows/{threadId}": {
            "delete": {
                "description": "Cancel an active workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Cancel Workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "threadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workflow cancelled successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/checkpoints": {
            "get": {
                "description": "List all checkpoints",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkpoint"
                ],
                "summary": "List Checkpoints",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Before thread ID for pagination",
                        "name": "before_thread_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Checkpoints listed successfully",
                        "schema": {
                            "$ref": "#/definitions/main.CheckpointListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Save a checkpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkpoint"
                ],
                "summary": "Put Checkpoint",
                "parameters": [
                    {
                        "description": "Put checkpoint request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.PutCheckpointRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Checkpoint saved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/checkpoints/{thread_id}": {
            "get": {
                "description": "Get a checkpoint by thread ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkpoint"
                ],
                "summary": "Get Checkpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "thread_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Checkpoint namespace",
                        "name": "checkpoint_ns",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Checkpoint retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.CheckpointResponse"
                        }
                    },
                    "404": {
                        "description": "Checkpoint not found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check the health status of the API gateway and all backend services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "Health check successful",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mealplan": {
            "get": {
                "description": "Get the current meal plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mealplan"
                ],
                "summary": "Get Meal Plan",
                "responses": {
                    "200": {
                        "description": "Meal plan retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealPlanResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Save the current meal plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mealplan"
                ],
                "summary": "Save Meal Plan",
                "parameters": [
                    {
                        "description": "Save meal plan request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.SaveMealPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meal plan saved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Not implemented",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mealplan/finalize": {
            "post": {
                "description": "Finalize the current meal plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mealplan"
                ],
                "summary": "Finalize Meal Plan",
                "parameters": [
                    {
                        "description": "Finalize meal plan request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.FinalizeMealPlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meal plan finalized successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mealplan/generate": {
            "post": {
                "description": "Generate a new meal plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mealplan"
                ],
                "summary": "Generate Meal Plan",
                "responses": {
                    "200": {
                        "description": "Meal plan generated successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealPlanResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mealplan/ics": {
            "get": {
                "description": "Get meal plan as ICS calendar file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/calendar"
                ],
                "tags": [
                    "mealplan"
                ],
                "summary": "Get Meal Plan ICS",
                "responses": {
                    "200": {
                        "description": "ICS calendar file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mealplan/replace": {
            "post": {
                "description": "Replace a meal in the plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Replace Meal",
                "parameters": [
                    {
                        "description": "Replace meal request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.ReplaceMealRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meal replaced successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals": {
            "get": {
                "description": "Get all available meals",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Get All Meals",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal type filter",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meals retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Create Meal",
                "parameters": [
                    {
                        "description": "Create meal request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.CreateMealRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Meal created successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals/swap": {
            "post": {
                "description": "Swap a meal with another",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Swap Meal",
                "parameters": [
                    {
                        "description": "Swap meal request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.SwapMealRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meal swapped successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals/{mealId}": {
            "put": {
                "description": "Update an existing meal's properties (name, effort, meal type, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Update Meal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update meal request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.UpdateMealRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meal updated successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Meal not found",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Delete Meal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Meal deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals/{mealId}/ingredients": {
            "post": {
                "description": "Add a new ingredient to a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Create Meal Ingredient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create ingredient request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.CreateMealIngredientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ingredient created successfully",
                        "schema": {
                            "$ref": "#/definitions/_go.CreateMealIngredientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals/{mealId}/ingredients/{ingredientId}": {
            "put": {
                "description": "Update an ingredient in a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Update Meal Ingredient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ingredient ID",
                        "name": "ingredientId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update ingredient request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.UpdateMealIngredientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ingredient updated successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an ingredient from a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Delete Meal Ingredient",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ingredient ID",
                        "name": "ingredientId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ingredient deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/main.MealResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals/{mealId}/steps": {
            "get": {
                "description": "Get recipe steps for a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "Get Recipe Steps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Steps retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.StepsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a recipe step to a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "Add Recipe Step",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add step request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.AddStepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Step added successfully",
                        "schema": {
                            "$ref": "#/definitions/main.StepResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete all recipe steps from a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "Delete All Recipe Steps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "All steps deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals/{mealId}/steps/bulk": {
            "post": {
                "description": "Add multiple recipe steps to a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "Add Bulk Recipe Steps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add bulk steps request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.AddBulkStepsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Steps added successfully",
                        "schema": {
                            "$ref": "#/definitions/main.StepsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals/{mealId}/steps/reorder": {
            "put": {
                "description": "Reorder recipe steps in a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "Reorder Recipe Steps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reorder steps request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.ReorderStepsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Steps reordered successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meals/{mealId}/steps/{stepId}": {
            "put": {
                "description": "Update a recipe step in a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "Update Recipe Step",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Step ID",
                        "name": "stepId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update step request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.UpdateStepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Step updated successfully",
                        "schema": {
                            "$ref": "#/definitions/main.StepResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a recipe step from a meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "steps"
                ],
                "summary": "Delete Recipe Step",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Step ID",
                        "name": "stepId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Step deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reconnect": {
            "post": {
                "description": "Reconnect to backend services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Reconnect",
                "responses": {
                    "200": {
                        "description": "Reconnect successful",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/shoppinglist": {
            "post": {
                "description": "Get shopping list for meal plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shopping"
                ],
                "summary": "Get Shopping List",
                "parameters": [
                    {
                        "description": "Shopping list request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.GetShoppingListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Shopping list retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.ShoppingListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{threadId}": {
            "get": {
                "description": "Get the current state of a workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflow"
                ],
                "summary": "Get Workflow State",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "threadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workflow state retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.WorkflowStateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{threadId}/abandon": {
            "post": {
                "description": "Abandon a workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflow"
                ],
                "summary": "Abandon Workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "threadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workflow abandoned successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{threadId}/messages": {
            "get": {
                "description": "Get all messages for a workflow thread",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflow"
                ],
                "summary": "Get Messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "threadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Messages retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/main.GetMessagesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a message to a workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflow"
                ],
                "summary": "Add Message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "threadId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add message request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.AddMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message added successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{threadId}/state": {
            "put": {
                "description": "Update the state of a workflow session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflow"
                ],
                "summary": "Update Session State",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Thread ID",
                        "name": "threadId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update session state request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/_go.UpdateSessionStateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session state updated successfully",
                        "schema": {
                            "$ref": "#/definitions/main.SimpleMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "_go.AddBulkStepsRequest": {
            "type": "object",
            "properties": {
                "instructions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meal_id": {
                    "type": "integer"
                }
            }
        },
        "_go.AddMessageRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "sender": {
                    "description": "\"user\" or \"agent\"",
                    "type": "string"
                },
                "thread_id": {
                    "type": "string"
                }
            }
        },
        "_go.AddStepRequest": {
            "type": "object",
            "properties": {
                "meal_id": {
                    "type": "integer"
                },
                "step": {
                    "$ref": "#/definitions/_go.Step"
                }
            }
        },
        "_go.AgentCheckpoint": {
            "type": "object",
            "properties": {
                "next": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "state": {
                    "$ref": "#/definitions/_go.MealPlanningCheckpointState"
                },
                "step": {
                    "type": "integer"
                }
            }
        },
        "_go.AgentCheckpointMetadata": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "step": {
                    "type": "integer"
                }
            }
        },
        "_go.CreateMealIngredientRequest": {
            "type": "object",
            "properties": {
                "ingredient": {
                    "$ref": "#/definitions/_go.Ingredient"
                },
                "meal_id": {
                    "type": "integer"
                }
            }
        },
        "_go.CreateMealIngredientResponse": {
            "type": "object",
            "properties": {
                "meal": {
                    "$ref": "#/definitions/_go.Meal"
                }
            }
        },
        "_go.CreateMealRequest": {
            "type": "object",
            "properties": {
                "meal": {
                    "$ref": "#/definitions/_go.Meal"
                }
            }
        },
        "_go.FeedbackEntryProto": {
            "type": "object",
            "properties": {
                "from": {
                    "description": "\"user\" or agent id",
                    "type": "string"
                },
                "meal_plan_version": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                }
            }
        },
        "_go.FinalizeMealPlanRequest": {
            "type": "object",
            "properties": {
                "plan": {
                    "$ref": "#/definitions/_go.WeeklyMealPlan"
                }
            }
        },
        "_go.GetShoppingListRequest": {
            "type": "object",
            "properties": {
                "plan": {
                    "description": "meal IDs",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "_go.Ingredient": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "meal_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "_go.Meal": {
            "type": "object",
            "properties": {
                "effort": {
                    "type": "integer"
                },
                "has_red_meat": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/_go.Ingredient"
                    }
                },
                "last_planned": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "meal_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/_go.Step"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "_go.MealPlanEntry": {
            "type": "object",
            "properties": {
                "day_index": {
                    "type": "integer"
                },
                "meal": {
                    "$ref": "#/definitions/_go.Meal"
                },
                "meal_type": {
                    "type": "string"
                }
            }
        },
        "_go.MealPlanningCheckpointState": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "current_step": {
                    "type": "string"
                },
                "feedback_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/_go.FeedbackEntryProto"
                    }
                },
                "is_finalized": {
                    "type": "boolean"
                },
                "iteration_count": {
                    "type": "integer"
                },
                "meal_plan": {
                    "$ref": "#/definitions/_go.WeeklyMealPlan"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "shopping_list": {
                    "$ref": "#/definitions/_go.ShoppingList"
                },
                "thread_id": {
                    "type": "string"
                },
                "updated_at": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                }
            }
        },
        "_go.PutCheckpointRequest": {
            "type": "object",
            "properties": {
                "checkpoint": {
                    "$ref": "#/definitions/_go.AgentCheckpoint"
                },
                "checkpoint_ns": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/_go.AgentCheckpointMetadata"
                },
                "thread_id": {
                    "type": "string"
                },
                "workflow_type": {
                    "type": "string"
                }
            }
        },
        "_go.ReorderStepsRequest": {
            "type": "object",
            "properties": {
                "meal_id": {
                    "type": "integer"
                },
                "step_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "_go.ReplaceMealRequest": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "new_meal_id": {
                    "type": "integer"
                }
            }
        },
        "_go.SaveMealPlanRequest": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/_go.MealPlanEntry"
                    }
                },
                "thread_id": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "_go.ShoppingList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/_go.ShoppingListItem"
                    }
                }
            }
        },
        "_go.ShoppingListItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "ingredient": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                }
            }
        },
        "_go.Step": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "instruction": {
                    "type": "string"
                },
                "meal_id": {
                    "type": "integer"
                },
                "step_number": {
                    "type": "integer"
                }
            }
        },
        "_go.SwapMealRequest": {
            "type": "object",
            "properties": {
                "meal_id": {
                    "type": "integer"
                },
                "meal_type": {
                    "type": "string"
                }
            }
        },
        "_go.UpdateMealIngredientRequest": {
            "type": "object",
            "properties": {
                "ingredient": {
                    "$ref": "#/definitions/_go.Ingredient"
                },
                "ingredient_id": {
                    "type": "integer"
                },
                "meal_id": {
                    "type": "integer"
                }
            }
        },
        "_go.UpdateMealRequest": {
            "type": "object",
            "properties": {
                "meal": {
                    "$ref": "#/definitions/_go.Meal"
                },
                "meal_id": {
                    "type": "integer"
                }
            }
        },
        "_go.UpdateSessionStateRequest": {
            "type": "object",
            "properties": {
                "current_step": {
                    "type": "string"
                },
                "meal_plan": {
                    "description": "JSON string",
                    "type": "string"
                },
                "shopping_list": {
                    "description": "JSON string",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "thread_id": {
                    "type": "string"
                }
            }
        },
        "_go.UpdateStepRequest": {
            "type": "object",
            "properties": {
                "meal_id": {
                    "type": "integer"
                },
                "step": {
                    "$ref": "#/definitions/_go.Step"
                },
                "step_id": {
                    "type": "integer"
                }
            }
        },
        "_go.WeeklyMealPlan": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/_go.MealPlanEntry"
                    }
                },
                "shopping_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/_go.ShoppingListItem"
                    }
                }
            }
        },
        "main.AgentMessageRequestBody": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "interactive": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "threadId": {
                    "type": "string"
                }
            }
        },
        "main.AgentMessageResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "$ref": "#/definitions/main.AgentResponseBody"
                }
            }
        },
        "main.AgentResponseBody": {
            "type": "object",
            "properties": {
                "currentStep": {
                    "type": "string"
                },
                "initialState": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "threadId": {
                    "type": "string"
                }
            }
        },
        "main.AgentStartRequestBody": {
            "type": "object",
            "properties": {
                "participants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "workflowType": {
                    "type": "string"
                }
            }
        },
        "main.AgentStartResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "$ref": "#/definitions/main.AgentResponseBody"
                }
            }
        },
        "main.CheckpointListResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "checkpointNs": {
                                "type": "string"
                            },
                            "threadId": {
                                "type": "string"
                            },
                            "tuple": {
                                "$ref": "#/definitions/main.CheckpointTupleResponse"
                            }
                        }
                    }
                }
            }
        },
        "main.CheckpointResponse": {
            "type": "object",
            "properties": {
                "found": {
                    "type": "boolean"
                },
                "tuple": {
                    "type": "object",
                    "properties": {
                        "checkpoint": {
                            "type": "object",
                            "properties": {
                                "state": {
                                    "type": "object",
                                    "properties": {
                                        "currentStep": {
                                            "type": "string"
                                        },
                                        "mealPlan": {
                                            "type": "object",
                                            "properties": {
                                                "days": {
                                                    "type": "array",
                                                    "items": {
                                                        "$ref": "#/definitions/main.MealPlanEntryResponse"
                                                    }
                                                }
                                            }
                                        },
                                        "participants": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        "threadId": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "main.CheckpointTupleResponse": {
            "type": "object",
            "properties": {
                "checkpoint": {
                    "type": "object",
                    "properties": {
                        "state": {
                            "type": "object",
                            "properties": {
                                "currentStep": {
                                    "type": "string"
                                },
                                "mealPlan": {
                                    "type": "object",
                                    "properties": {
                                        "days": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/main.MealPlanEntryResponse"
                                            }
                                        }
                                    }
                                },
                                "participants": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "threadId": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "main.GetMessagesResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.MessageResponse"
                    }
                }
            }
        },
        "main.HealthResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "main.IngredientResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "mealId": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "main.MealPlanEntryResponse": {
            "type": "object",
            "properties": {
                "dayIndex": {
                    "type": "integer"
                },
                "meal": {
                    "$ref": "#/definitions/main.MealResponse"
                },
                "mealType": {
                    "type": "string"
                }
            }
        },
        "main.MealPlanResponse": {
            "type": "object",
            "properties": {
                "plan": {
                    "type": "object",
                    "properties": {
                        "days": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.MealPlanEntryResponse"
                            }
                        },
                        "shoppingList": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.ShoppingListItemResponse"
                            }
                        }
                    }
                }
            }
        },
        "main.MealResponse": {
            "type": "object",
            "properties": {
                "effort": {
                    "type": "integer"
                },
                "hasRedMeat": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.IngredientResponse"
                    }
                },
                "lastPlanned": {
                    "type": "string",
                    "format": "date-time"
                },
                "mealType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.StepResponse"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "main.MealsResponse": {
            "type": "object",
            "properties": {
                "meals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.MealResponse"
                    }
                }
            }
        },
        "main.MessageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                },
                "threadId": {
                    "type": "string"
                }
            }
        },
        "main.ShoppingListItemResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "ingredient": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                }
            }
        },
        "main.ShoppingListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.ShoppingListItemResponse"
                    }
                }
            }
        },
        "main.SimpleMessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "main.StepResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "instruction": {
                    "type": "string"
                },
                "mealId": {
                    "type": "integer"
                },
                "stepNumber": {
                    "type": "integer"
                }
            }
        },
        "main.StepsResponse": {
            "type": "object",
            "properties": {
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.StepResponse"
                    }
                }
            }
        },
        "main.WorkflowMessageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                },
                "threadId": {
                    "type": "string"
                }
            }
        },
        "main.WorkflowStateResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.WorkflowMessageResponse"
                    }
                },
                "plan": {
                    "type": "object",
                    "properties": {
                        "days": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.MealPlanEntryResponse"
                            }
                        }
                    }
                },
                "shoppingList": {
                    "type": "object",
                    "properties": {
                        "items": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.ShoppingListItemResponse"
                            }
                        }
                    }
                }
            }
        },
        "main.WorkflowStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "object",
                    "properties": {
                        "currentStep": {
                            "type": "string"
                        },
                        "participants": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "threadId": {
                            "type": "string"
                        },
                        "workflowType": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "main.WorkflowsResponse": {
            "type": "object",
            "properties": {
                "workflows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.WorkflowStatusResponse"
                    }
                }
            }
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive.",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Meal Planner API Gateway",
	Description:      "API Gateway for Meal Planner service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
