// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/meal_planner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackendService_HealthCheck_FullMethodName          = "/mealplanner.BackendService/HealthCheck"
	BackendService_ReconnectDatabase_FullMethodName    = "/mealplanner.BackendService/ReconnectDatabase"
	BackendService_GetAllMeals_FullMethodName          = "/mealplanner.BackendService/GetAllMeals"
	BackendService_CreateMeal_FullMethodName           = "/mealplanner.BackendService/CreateMeal"
	BackendService_DeleteMeal_FullMethodName           = "/mealplanner.BackendService/DeleteMeal"
	BackendService_SwapMeal_FullMethodName             = "/mealplanner.BackendService/SwapMeal"
	BackendService_RemoveMeal_FullMethodName           = "/mealplanner.BackendService/RemoveMeal"
	BackendService_ReplaceMeal_FullMethodName          = "/mealplanner.BackendService/ReplaceMeal"
	BackendService_UpdateIngredient_FullMethodName     = "/mealplanner.BackendService/UpdateIngredient"
	BackendService_DeleteIngredient_FullMethodName     = "/mealplanner.BackendService/DeleteIngredient"
	BackendService_GetSteps_FullMethodName             = "/mealplanner.BackendService/GetSteps"
	BackendService_CreateStep_FullMethodName           = "/mealplanner.BackendService/CreateStep"
	BackendService_CreateStepsBulk_FullMethodName      = "/mealplanner.BackendService/CreateStepsBulk"
	BackendService_UpdateStep_FullMethodName           = "/mealplanner.BackendService/UpdateStep"
	BackendService_DeleteStep_FullMethodName           = "/mealplanner.BackendService/DeleteStep"
	BackendService_ReorderSteps_FullMethodName         = "/mealplanner.BackendService/ReorderSteps"
	BackendService_DeleteAllSteps_FullMethodName       = "/mealplanner.BackendService/DeleteAllSteps"
	BackendService_GetMealPlan_FullMethodName          = "/mealplanner.BackendService/GetMealPlan"
	BackendService_GenerateMealPlan_FullMethodName     = "/mealplanner.BackendService/GenerateMealPlan"
	BackendService_FinalizeMealPlan_FullMethodName     = "/mealplanner.BackendService/FinalizeMealPlan"
	BackendService_GetMealPlanIcs_FullMethodName       = "/mealplanner.BackendService/GetMealPlanIcs"
	BackendService_GenerateShoppingList_FullMethodName = "/mealplanner.BackendService/GenerateShoppingList"
	BackendService_StartWorkflow_FullMethodName        = "/mealplanner.BackendService/StartWorkflow"
	BackendService_SendMessage_FullMethodName          = "/mealplanner.BackendService/SendMessage"
	BackendService_GetWorkflowStatus_FullMethodName    = "/mealplanner.BackendService/GetWorkflowStatus"
	BackendService_ListWorkflows_FullMethodName        = "/mealplanner.BackendService/ListWorkflows"
	BackendService_CancelWorkflow_FullMethodName       = "/mealplanner.BackendService/CancelWorkflow"
	BackendService_GetWorkflowState_FullMethodName     = "/mealplanner.BackendService/GetWorkflowState"
	BackendService_AbandonWorkflow_FullMethodName      = "/mealplanner.BackendService/AbandonWorkflow"
	BackendService_AddMessageToWorkflow_FullMethodName = "/mealplanner.BackendService/AddMessageToWorkflow"
	BackendService_UpdateWorkflowState_FullMethodName  = "/mealplanner.BackendService/UpdateWorkflowState"
)

// BackendServiceClient is the client API for BackendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendServiceClient interface {
	// Health checks
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	ReconnectDatabase(ctx context.Context, in *ReconnectDatabaseRequest, opts ...grpc.CallOption) (*ReconnectDatabaseResponse, error)
	// Meal management
	GetAllMeals(ctx context.Context, in *GetAllMealsRequest, opts ...grpc.CallOption) (*GetAllMealsResponse, error)
	CreateMeal(ctx context.Context, in *CreateMealRequest, opts ...grpc.CallOption) (*CreateMealResponse, error)
	DeleteMeal(ctx context.Context, in *DeleteMealRequest, opts ...grpc.CallOption) (*DeleteMealResponse, error)
	SwapMeal(ctx context.Context, in *SwapMealRequest, opts ...grpc.CallOption) (*SwapMealResponse, error)
	RemoveMeal(ctx context.Context, in *RemoveMealRequest, opts ...grpc.CallOption) (*RemoveMealResponse, error)
	ReplaceMeal(ctx context.Context, in *ReplaceMealRequest, opts ...grpc.CallOption) (*ReplaceMealResponse, error)
	// Ingredient management
	UpdateIngredient(ctx context.Context, in *UpdateIngredientRequest, opts ...grpc.CallOption) (*UpdateIngredientResponse, error)
	DeleteIngredient(ctx context.Context, in *DeleteIngredientRequest, opts ...grpc.CallOption) (*DeleteIngredientResponse, error)
	// Recipe steps management
	GetSteps(ctx context.Context, in *GetStepsRequest, opts ...grpc.CallOption) (*GetStepsResponse, error)
	CreateStep(ctx context.Context, in *CreateStepRequest, opts ...grpc.CallOption) (*CreateStepResponse, error)
	CreateStepsBulk(ctx context.Context, in *CreateStepsBulkRequest, opts ...grpc.CallOption) (*CreateStepsBulkResponse, error)
	UpdateStep(ctx context.Context, in *UpdateStepRequest, opts ...grpc.CallOption) (*UpdateStepResponse, error)
	DeleteStep(ctx context.Context, in *DeleteStepRequest, opts ...grpc.CallOption) (*DeleteStepResponse, error)
	ReorderSteps(ctx context.Context, in *ReorderStepsRequest, opts ...grpc.CallOption) (*ReorderStepsResponse, error)
	DeleteAllSteps(ctx context.Context, in *DeleteAllStepsRequest, opts ...grpc.CallOption) (*DeleteAllStepsResponse, error)
	// Meal plan management
	GetMealPlan(ctx context.Context, in *GetMealPlanRequest, opts ...grpc.CallOption) (*GetMealPlanResponse, error)
	GenerateMealPlan(ctx context.Context, in *GenerateMealPlanRequest, opts ...grpc.CallOption) (*GenerateMealPlanResponse, error)
	FinalizeMealPlan(ctx context.Context, in *FinalizeMealPlanRequest, opts ...grpc.CallOption) (*FinalizeMealPlanResponse, error)
	GetMealPlanIcs(ctx context.Context, in *GetMealPlanIcsRequest, opts ...grpc.CallOption) (*GetMealPlanIcsResponse, error)
	// Shopping list
	GenerateShoppingList(ctx context.Context, in *GenerateShoppingListRequest, opts ...grpc.CallOption) (*GenerateShoppingListResponse, error)
	// Workflow/Agent management
	StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	GetWorkflowStatus(ctx context.Context, in *GetWorkflowStatusRequest, opts ...grpc.CallOption) (*GetWorkflowStatusResponse, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	CancelWorkflow(ctx context.Context, in *CancelWorkflowRequest, opts ...grpc.CallOption) (*CancelWorkflowResponse, error)
	// Workflow state management
	GetWorkflowState(ctx context.Context, in *GetWorkflowStateRequest, opts ...grpc.CallOption) (*GetWorkflowStateResponse, error)
	AbandonWorkflow(ctx context.Context, in *AbandonWorkflowRequest, opts ...grpc.CallOption) (*AbandonWorkflowResponse, error)
	AddMessageToWorkflow(ctx context.Context, in *AddMessageToWorkflowRequest, opts ...grpc.CallOption) (*AddMessageToWorkflowResponse, error)
	UpdateWorkflowState(ctx context.Context, in *UpdateWorkflowStateRequest, opts ...grpc.CallOption) (*UpdateWorkflowStateResponse, error)
}

type backendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendServiceClient(cc grpc.ClientConnInterface) BackendServiceClient {
	return &backendServiceClient{cc}
}

func (c *backendServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, BackendService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) ReconnectDatabase(ctx context.Context, in *ReconnectDatabaseRequest, opts ...grpc.CallOption) (*ReconnectDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconnectDatabaseResponse)
	err := c.cc.Invoke(ctx, BackendService_ReconnectDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetAllMeals(ctx context.Context, in *GetAllMealsRequest, opts ...grpc.CallOption) (*GetAllMealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMealsResponse)
	err := c.cc.Invoke(ctx, BackendService_GetAllMeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CreateMeal(ctx context.Context, in *CreateMealRequest, opts ...grpc.CallOption) (*CreateMealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMealResponse)
	err := c.cc.Invoke(ctx, BackendService_CreateMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) DeleteMeal(ctx context.Context, in *DeleteMealRequest, opts ...grpc.CallOption) (*DeleteMealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMealResponse)
	err := c.cc.Invoke(ctx, BackendService_DeleteMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SwapMeal(ctx context.Context, in *SwapMealRequest, opts ...grpc.CallOption) (*SwapMealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwapMealResponse)
	err := c.cc.Invoke(ctx, BackendService_SwapMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) RemoveMeal(ctx context.Context, in *RemoveMealRequest, opts ...grpc.CallOption) (*RemoveMealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMealResponse)
	err := c.cc.Invoke(ctx, BackendService_RemoveMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) ReplaceMeal(ctx context.Context, in *ReplaceMealRequest, opts ...grpc.CallOption) (*ReplaceMealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceMealResponse)
	err := c.cc.Invoke(ctx, BackendService_ReplaceMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) UpdateIngredient(ctx context.Context, in *UpdateIngredientRequest, opts ...grpc.CallOption) (*UpdateIngredientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIngredientResponse)
	err := c.cc.Invoke(ctx, BackendService_UpdateIngredient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) DeleteIngredient(ctx context.Context, in *DeleteIngredientRequest, opts ...grpc.CallOption) (*DeleteIngredientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIngredientResponse)
	err := c.cc.Invoke(ctx, BackendService_DeleteIngredient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetSteps(ctx context.Context, in *GetStepsRequest, opts ...grpc.CallOption) (*GetStepsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStepsResponse)
	err := c.cc.Invoke(ctx, BackendService_GetSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CreateStep(ctx context.Context, in *CreateStepRequest, opts ...grpc.CallOption) (*CreateStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStepResponse)
	err := c.cc.Invoke(ctx, BackendService_CreateStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CreateStepsBulk(ctx context.Context, in *CreateStepsBulkRequest, opts ...grpc.CallOption) (*CreateStepsBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStepsBulkResponse)
	err := c.cc.Invoke(ctx, BackendService_CreateStepsBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) UpdateStep(ctx context.Context, in *UpdateStepRequest, opts ...grpc.CallOption) (*UpdateStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStepResponse)
	err := c.cc.Invoke(ctx, BackendService_UpdateStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) DeleteStep(ctx context.Context, in *DeleteStepRequest, opts ...grpc.CallOption) (*DeleteStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStepResponse)
	err := c.cc.Invoke(ctx, BackendService_DeleteStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) ReorderSteps(ctx context.Context, in *ReorderStepsRequest, opts ...grpc.CallOption) (*ReorderStepsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReorderStepsResponse)
	err := c.cc.Invoke(ctx, BackendService_ReorderSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) DeleteAllSteps(ctx context.Context, in *DeleteAllStepsRequest, opts ...grpc.CallOption) (*DeleteAllStepsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAllStepsResponse)
	err := c.cc.Invoke(ctx, BackendService_DeleteAllSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetMealPlan(ctx context.Context, in *GetMealPlanRequest, opts ...grpc.CallOption) (*GetMealPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMealPlanResponse)
	err := c.cc.Invoke(ctx, BackendService_GetMealPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GenerateMealPlan(ctx context.Context, in *GenerateMealPlanRequest, opts ...grpc.CallOption) (*GenerateMealPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateMealPlanResponse)
	err := c.cc.Invoke(ctx, BackendService_GenerateMealPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) FinalizeMealPlan(ctx context.Context, in *FinalizeMealPlanRequest, opts ...grpc.CallOption) (*FinalizeMealPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeMealPlanResponse)
	err := c.cc.Invoke(ctx, BackendService_FinalizeMealPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetMealPlanIcs(ctx context.Context, in *GetMealPlanIcsRequest, opts ...grpc.CallOption) (*GetMealPlanIcsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMealPlanIcsResponse)
	err := c.cc.Invoke(ctx, BackendService_GetMealPlanIcs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GenerateShoppingList(ctx context.Context, in *GenerateShoppingListRequest, opts ...grpc.CallOption) (*GenerateShoppingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateShoppingListResponse)
	err := c.cc.Invoke(ctx, BackendService_GenerateShoppingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkflowResponse)
	err := c.cc.Invoke(ctx, BackendService_StartWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, BackendService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetWorkflowStatus(ctx context.Context, in *GetWorkflowStatusRequest, opts ...grpc.CallOption) (*GetWorkflowStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowStatusResponse)
	err := c.cc.Invoke(ctx, BackendService_GetWorkflowStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, BackendService_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) CancelWorkflow(ctx context.Context, in *CancelWorkflowRequest, opts ...grpc.CallOption) (*CancelWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelWorkflowResponse)
	err := c.cc.Invoke(ctx, BackendService_CancelWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) GetWorkflowState(ctx context.Context, in *GetWorkflowStateRequest, opts ...grpc.CallOption) (*GetWorkflowStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowStateResponse)
	err := c.cc.Invoke(ctx, BackendService_GetWorkflowState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) AbandonWorkflow(ctx context.Context, in *AbandonWorkflowRequest, opts ...grpc.CallOption) (*AbandonWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonWorkflowResponse)
	err := c.cc.Invoke(ctx, BackendService_AbandonWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) AddMessageToWorkflow(ctx context.Context, in *AddMessageToWorkflowRequest, opts ...grpc.CallOption) (*AddMessageToWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMessageToWorkflowResponse)
	err := c.cc.Invoke(ctx, BackendService_AddMessageToWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendServiceClient) UpdateWorkflowState(ctx context.Context, in *UpdateWorkflowStateRequest, opts ...grpc.CallOption) (*UpdateWorkflowStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkflowStateResponse)
	err := c.cc.Invoke(ctx, BackendService_UpdateWorkflowState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServiceServer is the server API for BackendService service.
// All implementations must embed UnimplementedBackendServiceServer
// for forward compatibility.
type BackendServiceServer interface {
	// Health checks
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	ReconnectDatabase(context.Context, *ReconnectDatabaseRequest) (*ReconnectDatabaseResponse, error)
	// Meal management
	GetAllMeals(context.Context, *GetAllMealsRequest) (*GetAllMealsResponse, error)
	CreateMeal(context.Context, *CreateMealRequest) (*CreateMealResponse, error)
	DeleteMeal(context.Context, *DeleteMealRequest) (*DeleteMealResponse, error)
	SwapMeal(context.Context, *SwapMealRequest) (*SwapMealResponse, error)
	RemoveMeal(context.Context, *RemoveMealRequest) (*RemoveMealResponse, error)
	ReplaceMeal(context.Context, *ReplaceMealRequest) (*ReplaceMealResponse, error)
	// Ingredient management
	UpdateIngredient(context.Context, *UpdateIngredientRequest) (*UpdateIngredientResponse, error)
	DeleteIngredient(context.Context, *DeleteIngredientRequest) (*DeleteIngredientResponse, error)
	// Recipe steps management
	GetSteps(context.Context, *GetStepsRequest) (*GetStepsResponse, error)
	CreateStep(context.Context, *CreateStepRequest) (*CreateStepResponse, error)
	CreateStepsBulk(context.Context, *CreateStepsBulkRequest) (*CreateStepsBulkResponse, error)
	UpdateStep(context.Context, *UpdateStepRequest) (*UpdateStepResponse, error)
	DeleteStep(context.Context, *DeleteStepRequest) (*DeleteStepResponse, error)
	ReorderSteps(context.Context, *ReorderStepsRequest) (*ReorderStepsResponse, error)
	DeleteAllSteps(context.Context, *DeleteAllStepsRequest) (*DeleteAllStepsResponse, error)
	// Meal plan management
	GetMealPlan(context.Context, *GetMealPlanRequest) (*GetMealPlanResponse, error)
	GenerateMealPlan(context.Context, *GenerateMealPlanRequest) (*GenerateMealPlanResponse, error)
	FinalizeMealPlan(context.Context, *FinalizeMealPlanRequest) (*FinalizeMealPlanResponse, error)
	GetMealPlanIcs(context.Context, *GetMealPlanIcsRequest) (*GetMealPlanIcsResponse, error)
	// Shopping list
	GenerateShoppingList(context.Context, *GenerateShoppingListRequest) (*GenerateShoppingListResponse, error)
	// Workflow/Agent management
	StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	GetWorkflowStatus(context.Context, *GetWorkflowStatusRequest) (*GetWorkflowStatusResponse, error)
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	CancelWorkflow(context.Context, *CancelWorkflowRequest) (*CancelWorkflowResponse, error)
	// Workflow state management
	GetWorkflowState(context.Context, *GetWorkflowStateRequest) (*GetWorkflowStateResponse, error)
	AbandonWorkflow(context.Context, *AbandonWorkflowRequest) (*AbandonWorkflowResponse, error)
	AddMessageToWorkflow(context.Context, *AddMessageToWorkflowRequest) (*AddMessageToWorkflowResponse, error)
	UpdateWorkflowState(context.Context, *UpdateWorkflowStateRequest) (*UpdateWorkflowStateResponse, error)
	mustEmbedUnimplementedBackendServiceServer()
}

// UnimplementedBackendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendServiceServer struct{}

func (UnimplementedBackendServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedBackendServiceServer) ReconnectDatabase(context.Context, *ReconnectDatabaseRequest) (*ReconnectDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconnectDatabase not implemented")
}
func (UnimplementedBackendServiceServer) GetAllMeals(context.Context, *GetAllMealsRequest) (*GetAllMealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMeals not implemented")
}
func (UnimplementedBackendServiceServer) CreateMeal(context.Context, *CreateMealRequest) (*CreateMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMeal not implemented")
}
func (UnimplementedBackendServiceServer) DeleteMeal(context.Context, *DeleteMealRequest) (*DeleteMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMeal not implemented")
}
func (UnimplementedBackendServiceServer) SwapMeal(context.Context, *SwapMealRequest) (*SwapMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapMeal not implemented")
}
func (UnimplementedBackendServiceServer) RemoveMeal(context.Context, *RemoveMealRequest) (*RemoveMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMeal not implemented")
}
func (UnimplementedBackendServiceServer) ReplaceMeal(context.Context, *ReplaceMealRequest) (*ReplaceMealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceMeal not implemented")
}
func (UnimplementedBackendServiceServer) UpdateIngredient(context.Context, *UpdateIngredientRequest) (*UpdateIngredientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIngredient not implemented")
}
func (UnimplementedBackendServiceServer) DeleteIngredient(context.Context, *DeleteIngredientRequest) (*DeleteIngredientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIngredient not implemented")
}
func (UnimplementedBackendServiceServer) GetSteps(context.Context, *GetStepsRequest) (*GetStepsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSteps not implemented")
}
func (UnimplementedBackendServiceServer) CreateStep(context.Context, *CreateStepRequest) (*CreateStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStep not implemented")
}
func (UnimplementedBackendServiceServer) CreateStepsBulk(context.Context, *CreateStepsBulkRequest) (*CreateStepsBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStepsBulk not implemented")
}
func (UnimplementedBackendServiceServer) UpdateStep(context.Context, *UpdateStepRequest) (*UpdateStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStep not implemented")
}
func (UnimplementedBackendServiceServer) DeleteStep(context.Context, *DeleteStepRequest) (*DeleteStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStep not implemented")
}
func (UnimplementedBackendServiceServer) ReorderSteps(context.Context, *ReorderStepsRequest) (*ReorderStepsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderSteps not implemented")
}
func (UnimplementedBackendServiceServer) DeleteAllSteps(context.Context, *DeleteAllStepsRequest) (*DeleteAllStepsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllSteps not implemented")
}
func (UnimplementedBackendServiceServer) GetMealPlan(context.Context, *GetMealPlanRequest) (*GetMealPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMealPlan not implemented")
}
func (UnimplementedBackendServiceServer) GenerateMealPlan(context.Context, *GenerateMealPlanRequest) (*GenerateMealPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMealPlan not implemented")
}
func (UnimplementedBackendServiceServer) FinalizeMealPlan(context.Context, *FinalizeMealPlanRequest) (*FinalizeMealPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeMealPlan not implemented")
}
func (UnimplementedBackendServiceServer) GetMealPlanIcs(context.Context, *GetMealPlanIcsRequest) (*GetMealPlanIcsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMealPlanIcs not implemented")
}
func (UnimplementedBackendServiceServer) GenerateShoppingList(context.Context, *GenerateShoppingListRequest) (*GenerateShoppingListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateShoppingList not implemented")
}
func (UnimplementedBackendServiceServer) StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWorkflow not implemented")
}
func (UnimplementedBackendServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedBackendServiceServer) GetWorkflowStatus(context.Context, *GetWorkflowStatusRequest) (*GetWorkflowStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflowStatus not implemented")
}
func (UnimplementedBackendServiceServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedBackendServiceServer) CancelWorkflow(context.Context, *CancelWorkflowRequest) (*CancelWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelWorkflow not implemented")
}
func (UnimplementedBackendServiceServer) GetWorkflowState(context.Context, *GetWorkflowStateRequest) (*GetWorkflowStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflowState not implemented")
}
func (UnimplementedBackendServiceServer) AbandonWorkflow(context.Context, *AbandonWorkflowRequest) (*AbandonWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbandonWorkflow not implemented")
}
func (UnimplementedBackendServiceServer) AddMessageToWorkflow(context.Context, *AddMessageToWorkflowRequest) (*AddMessageToWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessageToWorkflow not implemented")
}
func (UnimplementedBackendServiceServer) UpdateWorkflowState(context.Context, *UpdateWorkflowStateRequest) (*UpdateWorkflowStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkflowState not implemented")
}
func (UnimplementedBackendServiceServer) mustEmbedUnimplementedBackendServiceServer() {}
func (UnimplementedBackendServiceServer) testEmbeddedByValue()                        {}

// UnsafeBackendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServiceServer will
// result in compilation errors.
type UnsafeBackendServiceServer interface {
	mustEmbedUnimplementedBackendServiceServer()
}

func RegisterBackendServiceServer(s grpc.ServiceRegistrar, srv BackendServiceServer) {
	// If the following call pancis, it indicates UnimplementedBackendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendService_ServiceDesc, srv)
}

func _BackendService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_ReconnectDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconnectDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).ReconnectDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_ReconnectDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).ReconnectDatabase(ctx, req.(*ReconnectDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetAllMeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetAllMeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GetAllMeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetAllMeals(ctx, req.(*GetAllMealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CreateMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CreateMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_CreateMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CreateMeal(ctx, req.(*CreateMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_DeleteMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).DeleteMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_DeleteMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).DeleteMeal(ctx, req.(*DeleteMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SwapMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SwapMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_SwapMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SwapMeal(ctx, req.(*SwapMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_RemoveMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).RemoveMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_RemoveMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).RemoveMeal(ctx, req.(*RemoveMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_ReplaceMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).ReplaceMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_ReplaceMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).ReplaceMeal(ctx, req.(*ReplaceMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_UpdateIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).UpdateIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_UpdateIngredient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).UpdateIngredient(ctx, req.(*UpdateIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_DeleteIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).DeleteIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_DeleteIngredient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).DeleteIngredient(ctx, req.(*DeleteIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GetSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetSteps(ctx, req.(*GetStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CreateStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CreateStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_CreateStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CreateStep(ctx, req.(*CreateStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CreateStepsBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStepsBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CreateStepsBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_CreateStepsBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CreateStepsBulk(ctx, req.(*CreateStepsBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_UpdateStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).UpdateStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_UpdateStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).UpdateStep(ctx, req.(*UpdateStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_DeleteStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).DeleteStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_DeleteStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).DeleteStep(ctx, req.(*DeleteStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_ReorderSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).ReorderSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_ReorderSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).ReorderSteps(ctx, req.(*ReorderStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_DeleteAllSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).DeleteAllSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_DeleteAllSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).DeleteAllSteps(ctx, req.(*DeleteAllStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetMealPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMealPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetMealPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GetMealPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetMealPlan(ctx, req.(*GetMealPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GenerateMealPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMealPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GenerateMealPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GenerateMealPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GenerateMealPlan(ctx, req.(*GenerateMealPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_FinalizeMealPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeMealPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).FinalizeMealPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_FinalizeMealPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).FinalizeMealPlan(ctx, req.(*FinalizeMealPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetMealPlanIcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMealPlanIcsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetMealPlanIcs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GetMealPlanIcs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetMealPlanIcs(ctx, req.(*GetMealPlanIcsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GenerateShoppingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateShoppingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GenerateShoppingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GenerateShoppingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GenerateShoppingList(ctx, req.(*GenerateShoppingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_StartWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).StartWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_StartWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).StartWorkflow(ctx, req.(*StartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetWorkflowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetWorkflowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GetWorkflowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetWorkflowStatus(ctx, req.(*GetWorkflowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_CancelWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).CancelWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_CancelWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).CancelWorkflow(ctx, req.(*CancelWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_GetWorkflowState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetWorkflowState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GetWorkflowState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetWorkflowState(ctx, req.(*GetWorkflowStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_AbandonWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).AbandonWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_AbandonWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).AbandonWorkflow(ctx, req.(*AbandonWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_AddMessageToWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessageToWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).AddMessageToWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_AddMessageToWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).AddMessageToWorkflow(ctx, req.(*AddMessageToWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendService_UpdateWorkflowState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkflowStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).UpdateWorkflowState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_UpdateWorkflowState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).UpdateWorkflowState(ctx, req.(*UpdateWorkflowStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendService_ServiceDesc is the grpc.ServiceDesc for BackendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mealplanner.BackendService",
	HandlerType: (*BackendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _BackendService_HealthCheck_Handler,
		},
		{
			MethodName: "ReconnectDatabase",
			Handler:    _BackendService_ReconnectDatabase_Handler,
		},
		{
			MethodName: "GetAllMeals",
			Handler:    _BackendService_GetAllMeals_Handler,
		},
		{
			MethodName: "CreateMeal",
			Handler:    _BackendService_CreateMeal_Handler,
		},
		{
			MethodName: "DeleteMeal",
			Handler:    _BackendService_DeleteMeal_Handler,
		},
		{
			MethodName: "SwapMeal",
			Handler:    _BackendService_SwapMeal_Handler,
		},
		{
			MethodName: "RemoveMeal",
			Handler:    _BackendService_RemoveMeal_Handler,
		},
		{
			MethodName: "ReplaceMeal",
			Handler:    _BackendService_ReplaceMeal_Handler,
		},
		{
			MethodName: "UpdateIngredient",
			Handler:    _BackendService_UpdateIngredient_Handler,
		},
		{
			MethodName: "DeleteIngredient",
			Handler:    _BackendService_DeleteIngredient_Handler,
		},
		{
			MethodName: "GetSteps",
			Handler:    _BackendService_GetSteps_Handler,
		},
		{
			MethodName: "CreateStep",
			Handler:    _BackendService_CreateStep_Handler,
		},
		{
			MethodName: "CreateStepsBulk",
			Handler:    _BackendService_CreateStepsBulk_Handler,
		},
		{
			MethodName: "UpdateStep",
			Handler:    _BackendService_UpdateStep_Handler,
		},
		{
			MethodName: "DeleteStep",
			Handler:    _BackendService_DeleteStep_Handler,
		},
		{
			MethodName: "ReorderSteps",
			Handler:    _BackendService_ReorderSteps_Handler,
		},
		{
			MethodName: "DeleteAllSteps",
			Handler:    _BackendService_DeleteAllSteps_Handler,
		},
		{
			MethodName: "GetMealPlan",
			Handler:    _BackendService_GetMealPlan_Handler,
		},
		{
			MethodName: "GenerateMealPlan",
			Handler:    _BackendService_GenerateMealPlan_Handler,
		},
		{
			MethodName: "FinalizeMealPlan",
			Handler:    _BackendService_FinalizeMealPlan_Handler,
		},
		{
			MethodName: "GetMealPlanIcs",
			Handler:    _BackendService_GetMealPlanIcs_Handler,
		},
		{
			MethodName: "GenerateShoppingList",
			Handler:    _BackendService_GenerateShoppingList_Handler,
		},
		{
			MethodName: "StartWorkflow",
			Handler:    _BackendService_StartWorkflow_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _BackendService_SendMessage_Handler,
		},
		{
			MethodName: "GetWorkflowStatus",
			Handler:    _BackendService_GetWorkflowStatus_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _BackendService_ListWorkflows_Handler,
		},
		{
			MethodName: "CancelWorkflow",
			Handler:    _BackendService_CancelWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflowState",
			Handler:    _BackendService_GetWorkflowState_Handler,
		},
		{
			MethodName: "AbandonWorkflow",
			Handler:    _BackendService_AbandonWorkflow_Handler,
		},
		{
			MethodName: "AddMessageToWorkflow",
			Handler:    _BackendService_AddMessageToWorkflow_Handler,
		},
		{
			MethodName: "UpdateWorkflowState",
			Handler:    _BackendService_UpdateWorkflowState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/meal_planner.proto",
}
